Dhaigh94/Online-Portfolio

public/stylesheets/portfolio.css

This is to remove the border from the Work, Projects, Blog and Blog pages.

Remove Border

---

cypress/integration/Online-Portfolio/errorpages.js
cypress/integration/Online-Portfolio/home.js
cypress/integration/Online-Portfolio/navbar.js
views/404.ejs
views/500.ejs

This is to add some tests for the error pages.

Adding Error Page Tests

---

package-lock.json
package.json

Installing Cypress as a Dev Dependency

Install Cypress as a Dev Dependency

---

views/home.ejs

This is to update the Home Page.

Update Home Page

---

views/partials/footer.ejs

Fix Footer for Qantas Loyalty

---

README.md
package-lock.json
package.json

Updating Cypress to 3.8.0

---

README.md
package-lock.json
package.json
server.js
views/partials/footer.ejs
views/partials/footer500.ejs
views/partials/header.ejs
views/partials/header500.ejs

Change Bootstrap to use the NPM package instead of the CDN.

Use Bootstrap NPM package

---

README.md
package-lock.json
package.json
public/stylesheets/portfolio.css
views/404.ejs
views/blog.ejs
views/projects.ejs
views/work.ejs

Change Background Colour and Buttons.

Change Background Colour and Buttons

---

package-lock.json
package.json

Move Bootstrap as a Dependency.

Move Bootstrap as a Dependency

---

views/home.ejs
views/qantasairline.ejs

Updating copy for the Qantas job.

Update new Qantas Job

---

package-lock.json
package.json

Updating Cypress Version to 4.0.1

Update Cypress Version to 4.0.1

---

.circleci/config.yml
cypress.json
package-lock.json
package.json

Running the Cypress tests on the CI using Localhost.

Run CI Cypress tests on Localhost

---

package.json
server.js

This is to make localhost parameterised.

Make Localhost parameterised

---

.circleci/config.yml
cypress.json
cypress/integration/Online-Portfolio/errorpages.js
cypress/integration/Online-Portfolio/home.js
cypress/integration/Online-Portfolio/navbartests/navbar.js
cypress/integration/Online-Portfolio/navbartests/navbaripadlandscape.js
cypress/integration/Online-Portfolio/navbartests/navbaripadportrait.js
cypress/integration/Online-Portfolio/navbartests/navbarmobilelandscape.js
cypress/integration/Online-Portfolio/navbartests/navbarmobileportrait.js
cypress/integration/Online-Portfolio/socialmedia.js
package-lock.json
package.json

Updating the Circleci config file so it can run the Cypress tests on Localhost.

Fixing circleci to run the tests on Localhost

---

package.json

Add Percy Server Script

---

.circleci/config.yml
package.json

Add functionally to run Percy in the CI.

Add Percy Token to run Percy snapshot tests in the CI

---

README.md

Adding the CircleCI badge to the ReadMe file.

Add CircleCI badge to ReadMe file

---

.circleci/config.yml
cypress/integration/Online-Portfolio/navbartests/navbar.js
package-lock.json
package.json

Adding Artifacts to CircleCI for Screenshots and Videos.

Add Artifacts for CircleCI

---

.circleci/config.yml
cypress/integration/Online-Portfolio/work.js
views/workpages/work.ejs

Add more tests for the Work pages.

Add More Machines

---

cypress/integration/Online-Portfolio/projects.js

Add Cypress tests for the Projects pages.

Add Project tests

---

.circleci/config.yml

Change the Docker image for Cypress to fetch the latest one.

Change Docker Image to a NodeJS one

---

.circleci/config.yml

Using NodeJS Image for Real

---

cypress/integration/Online-Portfolio/blog.js

Adding Cypress Tests for the blog pages.

Add Blog Tests

---

README.md

Bring badges back

---

README.md

Remove the badges again that are broken.

Remove broken badges again

---

.circleci/config.yml
package.json

Add more machines to run in parallel to improve speed.

Add more machines to run in parallel

---

cypress/integration/Online-Portfolio/footer.js
package-lock.json
package.json
views/partials/header.ejs

Adding Cypress Tests for the Footer so we make sure it is not broken.

Footer tests

---

views/projectpages/rawapp.ejs
views/projectpages/rgbcolourgame.ejs

Fix the hyperlinks on 2 Project Pages.

Fix Hyperlinks

---

package-lock.json
package.json
public/stylesheets/portfolio.css

Change the colour of the hyperlinks to red and update some packages.

Red links and Package Update

---

README.md
public/stylesheets/portfolio.css
views/projectpages/cicypress.ejs

Add a Youtube link showing a walkthrough of my CI.

Add Youtube link on CI Page

---

server.js

Fix a security issue with jQuery.

Fix Security issue with jQuery

---

Gruntfile.js
package-lock.json
package.json

Add Grant Bumping to bump version.

Add Grant Bumping

---

Gruntfile.coffee

Fix Grunt Function

---

.github/workflows/main.yml

Fix GitHub actions

---

.github/workflows/main.yml

Fix version bumping again by making the token.

Fix file again

---

.github/workflows/main.yml

Change to v1

---

.github/workflows/main.yml

Add version bumping using Github Actions.

Create CircleCI file for version bumping

---

.github/workflows/main.yml

Rename the Workflow name for Github Actions.

Rename the Workflow name

---

.circleci/config.yml
README.md
package.json

Remove NPM install step

---

server.js
views/errorpages/404.ejs
views/errorpages/500.ejs

Updating the text on the error pages for 404 and 500.

Update the text on the error pages

---

package-lock.json
package.json
server.js
views/partials/footer.ejs
views/partials/footer500.ejs

Add the workaround to fix the security issue with jQuery.

Fixing Security Issue with jQuery

---

package-lock.json
package.json
server.js
views/partials/footer.ejs
views/partials/footer500.ejs

Remove the Jsdom and Dompurify packages. Also, update Jquery to 3.5.1 to fix the security issue.

Remove Jsdom, Dompurify and jQuery update

---

.circleci/config.yml
.gitignore
cypress.json
package-lock.json
package.json
reporter-config.json

Change Reporters

---

package.json

Fix Percy by adding a timeout so it does not show broken images.

Fix Percy by adding a timeout

---

README.md
package-lock.json
package.json

Adding a new Cypress Dashboard Badge to the Readme file and update the NPM packages.

Add Cypress Dashboard Badge and Update Packages

---

package-lock.json
package.json

Updating Cypress to version 5.

Upgrade to Cypress 5

---

.github/workflows/codeql-analysis.yml

Adding a Code Scan File to Scan to Codebase.

Create Code Scan File

---

SECURITY.md

Adding a Security Policy File.

Create Security Policy File

---

package-lock.json
package.json
views/other/home.ejs

Update the Home page as a copy change request and update the NPM packages.

Update Home page and packages

---

package-lock.json
package.json
server.js

Update Var to Const in the Server file and update popperjs.

Update var to const

---

views/other/contact.ejs

Add Millie Image to contact page

---

README.md
package-lock.json
package.json
views/blogpages/mytestingstory.ejs

Updating the Percy Badge on the Readme file also adding Nodemon.

Update Percy Badge

---

cypress/integration/blog.js
cypress/integration/errorpages.js
cypress/integration/home.js
cypress/integration/projects.js
cypress/integration/work.js
package-lock.json
package.json
public/stylesheets/portfolio.css
views/partials/header.ejs

Updating Bootstrap and Cypress.

Update Bootstrap and Cypress

---

README.md
cypress/integration/socialmedia.js
package-lock.json
package.json
views/partials/footer.ejs

Update the Instagram link and Npm packages

Update Instagram link

---

package-lock.json
package.json

Update NPM Engine

---

.github/workflows/create-release.yml

Adding a release GitHub script.

Add Release Script

---

.github/workflows/create-release.yml

Update the release script to trigger on Master

Update Release Script to trigger on Master

---

.github/workflows/create-release.yml

Fixing the create release script

Fix create release script

---

views/blogpages/blog.ejs
views/projectpages/projects.ejs
views/workpages/work.ejs

Update button colours

---

public/stylesheets/portfolio.css

Updating the background colour

Update the background colour

---

package-lock.json
package.json
views/workpages/qantasloyalty.ejs

Updating the Loyalty Page about the Travel Transition plus updating packages.

Update loyalty page

---

.github/workflows/bump-version.yml

Remove ruby from the github actions script.

Remove Ruby from script

---

.github/workflows/bump-version.yml
.github/workflows/has-version-bump-label.yml
package-lock.json
package.json

Add the GitHub Username and Email to secret plus update the packages.

Add to Secret

---

.github/workflows/bump-version.yml
.github/workflows/has-version-bump-label.yml

Update the version number on the scripts.

Update the versions on the script

---

views/partials/footer.ejs

Add the year on the projects on the footer links.

Add the year on the projects on footer

---

README.md

Removing the expired badges on the readme file.

Remove the expired badges on the readme file

---

.github/workflows/bump-version.yml
package.json

Update NPM Packages

---

package-lock.json
package.json

Updating NPM Packages as part of Maintenance. Also updating Percy Cli

Update NPM Packages Maintenance
